// abstract class AppStrings {
//   static const appName = "كنافة سكرة",
//   all = "الكل",
//       rateApp =  'قيم تطبيق ',
//       welcomeToKonafaSokar = "مرحبا بك في كنافة سكرة",
//       thanks = 'شكرا لك',
//       clickStarToRate = 'اضغط علي النجوم لاعطاء التقييم',
//       skip = "تخطي",
//       addToCart= "اضف الي السله",
//     allTypeOfDesert =   'جميع انواع الحلويات الشرقية و الغربية',
//       choiceAllType =       'اختر جميع الانواع و احصل علي العرض المفضل لديك',
//       otpCode = "رمز OTP ",
//       categories  = ' التصنيفات',
//       recipes = 'المكونات',
//       additions = 'الاضافات',
//       makeAdditionAsYouNeed = '(قم بتحديد الاضافه المناسبه علي حسب رغبتك)',
//       quantity = 'الكمية',
//       describeLocationHint = "اكتب وصفا لموقعك",
//       otpVerification = 'التحقق من OTP',
//       createNewAccount = "انشاء حساب جديد !",
//       welcome = "مرحبا بك  ",
//       yourLocation = " حدد موقعك"  ,
//       searchForYourLocation = "ابحث عن موقعك",
//       confirmAddress = "تأكيد العنوان",
//       steps = 'خطوة',
//       dailyOffers = 'العروض اليومية',
// bestSeller = 'الاكثر مبيعا',
//       welcomeBack = "مرحبا بعودتك !",
//       firstName = "الاسم الاول",
//       lastName = "الاسم الاخير",
//       phone = 'رقم هاتفك',
//       checkout = 'الدفع',
//       paymentMethod = 'طريقة الدفع',
//       cashOnDelivery = 'الدفع عند الاستلام',
//       visa = 'VISA',
// addNewAddress = 'اضف عنوان جديد',
//       emailHint = "بريدك الالكتروني",
//       birthday = 'تاريخ ميلادك',
//       next = 'اكمل',
//       shareApp = 'مشاركه التطبيق',
//       deliveryCost = 'تكلفة التوصيل',
//       deliveryAddress = 'عنوان التوصيل',
//       productsPrice = 'سعر المنتجات',
//       totalPrice = 'المبلغ الاجمالي',
//       currentPassword = 'كلمة المرور الحالية',
//       newPasswordShouldHaveKeyAndNumber  = 'يجب ان تحتوي كلمه المرور الجديدة علي حروف و ارقام و رموز ',
//       // newPassword = 'كلمة المرور الجديدة',
//       // confirmPassword = 'تأكيد كلمة المرور',
//       personalData = "البيانات الشخصية",
//       goToPay = 'انتقل إلى الدفع',
//       allNotifications ='السماح بتلقي الإشعارات',
//       allowAllNotificationFromApp =  'السماح بتلقي جميع الإشعارات الخاصة بالتطبيق',
//       signInSuccessfully =
//           ' لقد قمت بتسجيل الدخول بنجاح \n في تطبيق دليل المدينه',
//       goToHome = "الذهاب الى الصفحه الرئيسية",
//       signIn = "سجل دخول",
//       logout = 'تسجيل الخروج',
//       logoutConfirmation = 'هل انت متأكد من تسجيل الخروج ؟',
//       register = " تسجيل جديد",
//       otpVerificationSubTitle =
//           'يرجى التحقق من بريدك الإلكتروني للحصول على رمز التحقق',
//       welcomeInLogin = 'مرحبا بك مره اخرى فى تطبيق دليل المدينه',
//       enterPasswordHint = 'أدخل كلمة المرور الخاصة بك',
//       verifyEmail = "تأكيد البريد الاكتروني",
//       dontHaveAnAccount = "ليس لديك حساب؟ ",
//       haveAnAccount = 'لديك حساب بالفعل ؟ ',
//       resendCode = "إعادة إرسال الرمز",
//       letsStart = "هيا نبدأ !",
//       favorite = 'المفضله',
//       places = "اماكن",
//       orderNumber = 'رقم الطلب',
//       numberOfPieces = 'عدد القطع',
//       notification = 'الاشعارات',
//       settings = 'الاعدادات',
//       privacy = 'الخصوصيه',
//       public = 'عام',
//       price = 'السعر',
//       totally = '/الاجمالي',
//       language = 'اللغه',
//       likeIt = 'لقد اعجبتك ',
//       deleteAccount = 'حذف الحساب',
//       deleteAccountConfirmation = 'هل انت متأكد من حذف الحساب ؟',
//       privacyPolicy = 'سياسة الدعم',
//       darkMode = 'الوضع المظلم',
//       myOrder = 'طلباتي',
//       myOrderDetails = 'تفاصيل الطلب',
//       areYouSureToDeleteAccount = 'هل انت متأكد من حذف الحساب ؟',
//       areYouSureToLogOut = 'هل انت متأكد من تسجيل الخروج ؟',
//       delete = 'حذف',
//       cancel = 'الغاء',
//       yes = 'نعم',
//       collectAndWin ='جمع واكسب', 
//       collectPointsAndWin =  '  جمع نقط و اكسب معانا خصم يصل الي 70% ',
//       settingsPersonalInfo = "اعدادات الملف الشخصى",
//       personalInfoData = "بيانات الملف الشخصى",
//       introText =
//           "قم بتسجيل الدخول لتستمتع بالميزات التي نقدمها، وواستكشف اماكن جديده!",
//       home = "الرئيسية",
//       dailyGoals = "الاهداف اليومية",
//       monthlyGoals = "الاهداف الشهرية",
//       visit6Doctors = " قم بزيارة 6 اطباءاليوم",
//       dailyMissonsDone = "قمت بتحقيق 60% من هدفك اليومي",
//       monthlyMissonsDone = "قمت بتحقيق 60% من هدفك الشهري",
//       requiredPoints = "النقاط المطلوبة",
//       currentPoints = "النقاط الحالية",
//       collectPointAndGetGift = 'جمع عدد النقاط المطلوبه و احصل علي هديتك مجانا ',
//       redeemNow = 'استبدل الان',
//       dailuPlane = "الخطه اليوميه",
//       addDailyPlan = "اضافة الخطة اليومية",
//       creatAcount = "انشئ حساب",
//       verifyAndFollow = 'التحقق والمتابعة',
//       hintName = "ادخل اسمك ثلاثي",
//       addNewVisit = 'اضف زياره جديده',
//       hintPassword = "ادخل كلمة المرور",
//       changePassword = 'تغيير الرقم السرى',
//       hintChangePassword = 'تغيير كلمه المرور الخاصه بك',
//       hintConfirmPassword = "ادخل كلمة المرور مرة اخري",
//       confirmOtp = "تأكيد كود التسجيل",
//       otpMessage = "يرجى التحقق من بريدك الإلكتروني للحصول على رمز التحقق",
//       email = "البريد الالكتروني",
//       forgetPasswordMessage =
//           'أدخل حساب بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك.',
//       name = "الاسم",
//       password = "كلمة المرور",
//       newPassword = "كلمة المرور الجديدة",
//       confirmNewPassword = "تأكيد كلمة المرور الجديدة",
//       resetPassword = "إعادة تعيين كلمة المرور",
//       confirm = "تأكيد",
//       send = "ارسال",
//       signout = "تسجيل الخروج",
//       confirmPassword = "تأكيد كلمة المرور",
//       forgetPassword = "هل نسيت كلمة المرور ؟",
//       confirmationCode = "كود التسجيل",
//       confirmationCodeemail = "رمز التحقق",
//       typeOfRepersentative = "نوع المندوب",
//       scienstific = "علمي",
//       sales = "تجاري",
//       createAccount = "انشئ حساب",
//       haveAnAccoun = "لديك حساب بالفعل ؟ ",
//       signInNow = "تسجيل الدخول ",
//       hintConfirmationCode = "ادخل كود التسجيل الخاص بك",
//       selectPurpose = "حدد نوع الهدف",
//       selectActiveIngredient = "حدد المادة الفعالة",
//       selectAppointment = "حدد الموعد",
//       visitDate = "تاريخ الزيارة",
//       time = "الوقت",
//       addPurposeOfplan = "اضف الهدف من الخطة",
//       addToPlan = "اضف الي الخطه",
//       choosePlans = "اختار الاهداف",
//       details = "الملاحظات",
//       addYourDetails = "ادخل ملاحظاتك هنا",
//       saveDetails = "حفظ الملاحظات",
//       reports = "التقارير",
//       showDetails = "عرض التفاصيل",
//       prizes = "المكافـأت",
//       rewardedPrizes = "المكافـأت المكتسبة",
//       viewRewards = "عرض المكافئات",
//       previousRewards = " المكافئات السابقة",
//       profile = "الصفحة الشخصية",
//       trackOrder = "تتبع طلبك",
//       points = "النقاط",
//       point = 'نقط',
//       pointsEarned = 'النقاط المكتسبه', 
//       youWillGetAGift = 'ستحصل علي هديتك  عند حصولك علي250 نقطة اضافية',
//       rewards = "المكافأت",
//       earnExtraPoints =  'اكسب نقاط إضافية',
//       cart = "السلة",
//       performanceDetails = "احصائيات الاداء",
//       editProfile = "تعديل الملف الشخصى",
//       personalInfo = "المعلومات الشخصية",
//       phoneHint = "ادخل رقم الهاتف",
//       visitsHint = "ادخل عدد الزيارات المكتملة",
//       goalsHint = "ادخل عدد الاهداف المحققة",
//       activeSubstanceHint = "ادخل افضل مادة فعالة",
//       uncompletedVisitsHint = "ادخل عدد الزيارات الغير مكتملة",
//       save = "حفظ",
//       invalidForm = "البيانات غير صحيحة",
//       recognize = "تعرف على ",
//       bestRestaurants = "افضل المطاعم القريبه منك",
//       passwordMismatch = "كلمة المرور غير متطابقة",
//       bestRestaurantsCafes = "افضل المطاعم والكافيهات",
//       extraSuggestion = "اقتراحات اضافيه",
//       ratings = "التقيمات",
//       searchFor = "ابحث عما تريد....",
//       addCommit = 'اضف تقييمك',
//       sendCommit = 'ارسال التقييم',
//       edit = 'تعديل',
//       youThinkOfTheRestaurant = 'ما رايك فى تجربه المطعم؟',
//       feedbackWillHelpImprove = 'ستساعد ملاحظاتك في تحسين تجربة التطبيق',
//       personalProfile = "الملف الشخصى",

//       myName = "احمد سلمان ";
// }


import 'package:easy_localization/easy_localization.dart';

abstract class AppStrings {
  static String get appName => 'appName'.tr();
  static String get all => 'all'.tr();
  static String get rateApp => 'rateApp'.tr();
  static String get welcomeToKonafaSokar => 'welcomeToKonafaSokar'.tr();
  static String get thanks => 'thanks'.tr();
  static String get clickStarToRate => 'clickStarToRate'.tr();
  static String get skip => 'skip'.tr();
  static String get addToCart => 'addToCart'.tr();
  static String get allTypeOfDesert => 'allTypeOfDesert'.tr();
  static String get choiceAllType => 'choiceAllType'.tr();
  static String get otpCode => 'otpCode'.tr();
  static String get categories => 'categories'.tr();
  static String get recipes => 'recipes'.tr();
  static String get additions => 'additions'.tr();
  static String get makeAdditionAsYouNeed => 'makeAdditionAsYouNeed'.tr();
  static String get quantity => 'quantity'.tr();
  static String get describeLocationHint => 'describeLocationHint'.tr();
  static String get otpVerification => 'otpVerification'.tr();
  static String get createNewAccount => 'createNewAccount'.tr();
  static String get welcome => 'welcome'.tr();
  static String get yourLocation => 'yourLocation'.tr();
  static String get searchForYourLocation => 'searchForYourLocation'.tr();
  static String get confirmAddress => 'confirmAddress'.tr();
  static String get steps => 'steps'.tr();
  static String get dailyOffers => 'dailyOffers'.tr();
  static String get bestSeller => 'bestSeller'.tr();
  static String get welcomeBack => 'welcomeBack'.tr();
  static String get firstName => 'firstName'.tr();
  static String get lastName => 'lastName'.tr();
  static String get phone => 'phone'.tr();
  static String get checkout => 'checkout'.tr();
  static String get paymentMethod => 'paymentMethod'.tr();
  static String get cashOnDelivery => 'cashOnDelivery'.tr();
  static String get visa => 'visa'.tr();
  static String get addNewAddress => 'addNewAddress'.tr();
  static String get emailHint => 'emailHint'.tr();
  static String get birthday => 'birthday'.tr();
  static String get next => 'next'.tr();
  static String get shareApp => 'shareApp'.tr();
  static String get deliveryCost => 'deliveryCost'.tr();
  static String get deliveryAddress => 'deliveryAddress'.tr();
  static String get productsPrice => 'productsPrice'.tr();
  static String get totalPrice => 'totalPrice'.tr();
  static String get currentPassword => 'currentPassword'.tr();
  static String get newPasswordShouldHaveKeyAndNumber => 'newPasswordShouldHaveKeyAndNumber'.tr();
  static String get personalData => 'personalData'.tr();
  static String get goToPay => 'goToPay'.tr();
  static String get allNotifications => 'allNotifications'.tr();
  static String get allowAllNotificationFromApp => 'allowAllNotificationFromApp'.tr();
  static String get signInSuccessfully => 'signInSuccessfully'.tr();
  static String get goToHome => 'goToHome'.tr();
  static String get signIn => 'signIn'.tr();
  static String get logout => 'logout'.tr();
  static String get logoutConfirmation => 'logoutConfirmation'.tr();
  static String get register => 'register'.tr();
  static String get otpVerificationSubTitle => 'otpVerificationSubTitle'.tr();
  static String get welcomeInLogin => 'welcomeInLogin'.tr();
  static String get enterPasswordHint => 'enterPasswordHint'.tr();
  static String get verifyEmail => 'verifyEmail'.tr();
  static String get dontHaveAnAccount => 'dontHaveAnAccount'.tr();
  static String get haveAnAccount => 'haveAnAccount'.tr();
  static String get resendCode => 'resendCode'.tr();
  static String get letsStart => 'letsStart'.tr();
  static String get favorite => 'favorite'.tr();
  static String get places => 'places'.tr();
  static String get orderNumber => 'orderNumber'.tr();
  static String get numberOfPieces => 'numberOfPieces'.tr();
  static String get notification => 'notification'.tr();
  static String get settings => 'settings'.tr();
  static String get privacy => 'privacy'.tr();
  static String get public => 'public'.tr();
  static String get price => 'price'.tr();
  static String get totally => 'totally'.tr();
  static String get language => 'language'.tr();
  static String get likeIt => 'likeIt'.tr();
  static String get deleteAccount => 'deleteAccount'.tr();
  static String get deleteAccountConfirmation => 'deleteAccountConfirmation'.tr();
  static String get privacyPolicy => 'privacyPolicy'.tr();
  static String get darkMode => 'darkMode'.tr();
  static String get myOrder => 'myOrder'.tr();
  static String get myOrderDetails => 'myOrderDetails'.tr();
  static String get areYouSureToDeleteAccount => 'areYouSureToDeleteAccount'.tr();
  static String get areYouSureToLogOut => 'areYouSureToLogOut'.tr();
  static String get delete => 'delete'.tr();
  static String get cancel => 'cancel'.tr();
  static String get yes => 'yes'.tr();
  static String get collectAndWin => 'collectAndWin'.tr();
  static String get collectPointsAndWin => 'collectPointsAndWin'.tr();
  static String get settingsPersonalInfo => 'settingsPersonalInfo'.tr();
  static String get personalInfoData => 'personalInfoData'.tr();
  static String get introText => 'introText'.tr();
  static String get home => 'home'.tr();
  static String get dailyGoals => 'dailyGoals'.tr();
  static String get monthlyGoals => 'monthlyGoals'.tr();
  static String get visit6Doctors => 'visit6Doctors'.tr();
  static String get dailyMissonsDone => 'dailyMissonsDone'.tr();
  static String get monthlyMissonsDone => 'monthlyMissonsDone'.tr();
  static String get requiredPoints => 'requiredPoints'.tr();
  static String get currentPoints => 'currentPoints'.tr();
  static String get collectPointAndGetGift => 'collectPointAndGetGift'.tr();
  static String get redeemNow => 'redeemNow'.tr();
  static String get dailuPlane => 'dailuPlane'.tr();
  static String get addDailyPlan => 'addDailyPlan'.tr();
  static String get creatAcount => 'creatAcount'.tr();
  static String get verifyAndFollow => 'verifyAndFollow'.tr();
  static String get hintName => 'hintName'.tr();
  static String get addNewVisit => 'addNewVisit'.tr();
  static String get hintPassword => 'hintPassword'.tr();
  static String get changePassword => 'changePassword'.tr();
  static String get hintChangePassword => 'hintChangePassword'.tr();
  static String get hintConfirmPassword => 'hintConfirmPassword'.tr();
  static String get confirmOtp => 'confirmOtp'.tr();
  static String get otpMessage => 'otpMessage'.tr();
  static String get email => 'email'.tr();
  static String get forgetPasswordMessage => 'forgetPasswordMessage'.tr();
  static String get name => 'name'.tr();
  static String get password => 'password'.tr();
  static String get newPassword => 'newPassword'.tr();
  static String get confirmNewPassword => 'confirmNewPassword'.tr();
  static String get resetPassword => 'resetPassword'.tr();
  static String get confirm => 'confirm'.tr();
  static String get send => 'send'.tr();
  static String get signout => 'signout'.tr();
  static String get confirmPassword => 'confirmPassword'.tr();
  static String get forgetPassword => 'forgetPassword'.tr();
  static String get confirmationCode => 'confirmationCode'.tr();
  static String get confirmationCodeemail => 'confirmationCodeemail'.tr();
  static String get typeOfRepersentative => 'typeOfRepersentative'.tr();
  static String get scienstific => 'scienstific'.tr();
  static String get sales => 'sales'.tr();
  static String get createAccount => 'createAccount'.tr();
  static String get haveAnAccoun => 'haveAnAccoun'.tr();
  static String get signInNow => 'signInNow'.tr();
  static String get hintConfirmationCode => 'hintConfirmationCode'.tr();
  static String get selectPurpose => 'selectPurpose'.tr();
  static String get selectActiveIngredient => 'selectActiveIngredient'.tr();
  static String get selectAppointment => 'selectAppointment'.tr();
  static String get visitDate => 'visitDate'.tr();
  static String get time => 'time'.tr();
  static String get addPurposeOfplan => 'addPurposeOfplan'.tr();
  static String get addToPlan => 'addToPlan'.tr();
  static String get choosePlans => 'choosePlans'.tr();
  static String get details => 'details'.tr();
  static String get addYourDetails => 'addYourDetails'.tr();
  static String get saveDetails => 'saveDetails'.tr();
  static String get reports => 'reports'.tr();
  static String get showDetails => 'showDetails'.tr();
  static String get prizes => 'prizes'.tr();
  static String get rewardedPrizes => 'rewardedPrizes'.tr();
  static String get viewRewards => 'viewRewards'.tr();
  static String get previousRewards => 'previousRewards'.tr();
  static String get profile => 'profile'.tr();
  static String get trackOrder => 'trackOrder'.tr();
  static String get points => 'points'.tr();
  static String get point => 'point'.tr();
  static String get pointsEarned => 'pointsEarned'.tr();
  static String get youWillGetAGift => 'youWillGetAGift'.tr();
  static String get rewards => 'rewards'.tr();
  static String get earnExtraPoints => 'earnExtraPoints'.tr();
  static String get cart => 'cart'.tr();
  static String get performanceDetails => 'performanceDetails'.tr();
  static String get editProfile => 'editProfile'.tr();
  static String get personalInfo => 'personalInfo'.tr();
  static String get phoneHint => 'phoneHint'.tr();
  static String get visitsHint => 'visitsHint'.tr();
  static String get goalsHint => 'goalsHint'.tr();
  static String get activeSubstanceHint => 'activeSubstanceHint'.tr();
  static String get uncompletedVisitsHint => 'uncompletedVisitsHint'.tr();
  static String get save => 'save'.tr();
  static String get invalidForm => 'invalidForm'.tr();
  static String get recognize => 'recognize'.tr();
  static String get bestRestaurants => 'bestRestaurants'.tr();
  static String get passwordMismatch => 'passwordMismatch'.tr();
  static String get bestRestaurantsCafes => 'bestRestaurantsCafes'.tr();
  static String get extraSuggestion => 'extraSuggestion'.tr();
  static String get ratings => 'ratings'.tr();
  static String get searchFor => 'searchFor'.tr();
  static String get addCommit => 'addCommit'.tr();
  static String get sendCommit => 'sendCommit'.tr();
  static String get edit => 'edit'.tr();
  static String get youThinkOfTheRestaurant => 'youThinkOfTheRestaurant'.tr();
  static String get feedbackWillHelpImprove => 'feedbackWillHelpImprove'.tr();
  static String get personalProfile => 'personalProfile'.tr();
  static String get myName => 'myName'.tr();
}